php-version: majorminor
extensions: apcu,ast,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,iconv,libxml,mbregex,mbstring,opcache,openssl,pcntl,phar,posix,readline,session,simplexml,sockets,sodium,tokenizer,xml,xmlreader,xmlwriter,zip,zlib
shared-extensions: [amqp,brotli,bz2,dio,ds,ev,event,ffi,ftp,gd,gettext,gmp,gmssl,igbinary,imagick,inotify,intl,ldap,lz4,memcache,memcached,mongodb,msgpack,mysqli,mysqlnd,odbc,opentelemetry,parallel,pdo,pdo_mysql,pdo_odbc,pdo_pgsql,pdo_sqlite,pdo_sqlsrv,pgsql,protobuf,rar,redis,rdkafka,shmop,spx,sqlite3,sqlsrv,ssh2,swoole,sysvmsg,sysvsem,sysvshm,tidy,uuid,uv,xdebug,xhprof,xlswriter,xsl,xz,yac,yaml,zstd]
libs: [libacl, libavif, nghttp3, ngtcp2, watcher]
sapi: cli,embed,fpm,frankenphp
debug: false
build-options:
    enable-zts: true
    with-clean: false
    with-suggested-libs: true
    with-suggested-exts: false
    no-strip: false
    with-config-file-path: "/etc/php-zts.ini"
    with-config-file-scan-dir: "/etc/php-zts.d"
    # Hardcoded INI options for cli and micro SAPI (e.g. "memory_limit=4G", list accepted)
    with-hardcoded-ini: [ ]
    # UPX pack the binary (default: false)
    with-upx-pack: false

download-options:
    prefer-pre-built: false
    no-alt: false
    ignore-cache-sources: 'php-src'

craft-options:
    doctor: true
    download: true
    build: true

extra-env:
    # e.g. Use github token to avoid rate limit
    # GITHUB_TOKEN: your-github-token
    SPC_LIBC: glibc
    EXTENSION_DIR: /usr/lib64/php-zts/modules
    SPC_CMD_VAR_PHP_EMBED_TYPE: shared
    SPC_DEFAULT_C_FLAGS: "-fpic -O3 -fstack-protector-strong -fstack-clash-protection"
    SPC_DEFAULT_CXX_FLAGS: "-fpic -O3 -fstack-protector-strong -fstack-clash-protection"
    SPC_OPT_BUILD_ARGS: "--with-config-file-path=/etc/php-zts.ini --with-config-file-scan-dir=/etc/php-zts.d"
    SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS: "-g0 -fstack-protector-strong -O3 -fno-ident -fpic -fpie"
    SPC_CMD_VAR_PHP_MAKE_EXTRA_LDFLAGS: "-pie -release zts-majorminornodot"
    LDFLAGS: "-Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack"
    SPC_CMD_PREFIX_PHP_CONFIGURE: "./configure --prefix= --with-valgrind=no --disable-shared --enable-static --disable-all --disable-cgi --disable-phpdbg --disable-debug --with-pic --disable-dependency-tracking --enable-rtld-now"
    PHP_BUILD_PROVIDER: "Static PHP <https://static-php.dev> #StandWithUkraine"
