document: modulemd
version: 2
data:
    name: static-php
    stream: majorminor
    version: 20250603
    context: local
    summary: Static PHP majorminor packages
    description: Static PHP majorminor built from local RPMs
    license:
        module:
            - MIT
    dependencies:
        - buildrequires:
              platform:
                  - el7
                  - el8
                  - el9
                  - el10
          requires:
              platform:
                  - el7
                  - el8
                  - el9
                  - el10
    components:
        rpms:
            prefix:
                rationale: Main package
                ref: majorminorpatch
            prefix-cli:
                rationale: CLI
                ref: majorminorpatch
            prefix-fpm:
                rationale: FPM
                ref: majorminorpatch
            prefix-embed:
                rationale: Embed
                ref: majorminorpatch
    artifacts:
        rpms:
            - prefix-0:majorminorpatch-iteration.architecture
            - prefix-cli-0:majorminorpatch-iteration.architecture
            - prefix-fpm-0:majorminorpatch-iteration.architecture
            - prefix-embed-0:majorminorpatch-iteration.architecture
